[package]
name = "binary_rw"
version = "0.1.0"
edition = "2021"
authors = ["Phill030"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
anyhow = "1.0.71"